kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteMany
  #volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast
