apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-v1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fast
  nfs:          
    path: /var/lib/nfs/share/v1
    server: 192.168.1.88
