apiVersion: v1
kind: Pod
metadata:
  name: test-nfs
  namespace: default
spec:
  containers:
  - name: busybox
    image: hwchiu/netutils:latest
    volumeMounts:
      - name: nfs-volume
        mountPath: /nfs
  volumes:
    - name: nfs-volume
      nfs:
        server: 192.168.1.88
        path: /var/lib/nfs/share
