apiVersion: v1
kind: Service
metadata:
  name: hello-pod-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: hello-pod-port
  selector:
  # apply to the pods with label app=webserver
    app: webserver
  type: LoadBalancer
