apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-app
  labels:
    app: my-rc-app
spec:
  template:
    metadata:
      name: rc-pod
      labels:
        app: my-rc-pod
    spec:
      containers:
        - name: container-nginx
          image: nginx
  replicas: 3
