apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  ports:
  - port: 80
    targetPort: wordpress-port
    protocol: TCP
  selector:
    app: wordpress-deploy
  type: LoadBalancer
