apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server-deploy
  template:
    metadata:
      labels:
        app: mysql-server-deploy
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: db-password
        volumeMounts:
         - mountPath: "/var/lib/mysql"
           name: mysql-server-storage
      volumes:
      - name: mysql-server-storage
        persistentVolumeClaim:
          claimName: myclaim
