apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  db-password: YWJjZDEyMzQ=
  auth_key: YWJjZDEyMzQ=
  secure_auth_key: YWJjZDEyMzQ=
  logged_in_key: YWJjZDEyMzQ=
  nonce_key: YWJjZDEyMzQ=
