apiVersion: v1
kind: Pod
metadata:
  name: my-centos-volume
  labels:
    app: centos
spec:
  containers:
  - name: my-centos-volume
    image: centos:latest
    imagePullPolicy: IfNotPresent
    command: ["top","-b"]
    volumeMounts:
    - name: test-storage
      mountPath: /test
      subPath: test
  volumes:
    - name: test-storage
      persistentVolumeClaim: 
        claimName: myclaim
