apiVersion: v1
kind: Service
metadata:
  name: hello-service-lb
spec:
  #type: NodePort
  type: LoadBalancer
  ports:
  - port: 3000
#    nodePort: 30390
    protocol: TCP
    targetPort: 3000
  selector:
    app: my-deployment
