apiVersion: v1
kind: Pod
metadata:
  name: game-data-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh","-c","cat /etc/config/game.properties" ]
      args: ["; ls -al /etc/config/"]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: game-config
        items:
        - key: game.properties
          path: game.properties
  restartPolicy: Never
