apiVersion: v1
kind: Secret
metadata:
  name: demo-secret-from-yaml
type: Opaque
data:
  # need to use base64 to echo the data required to be protected
  # echo -n "password" | base64
  username: cm9vdA== 
  password: cm9vdHBhc3M=

